# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helmet', models.CharField(max_length=24)),
                ('chest', models.CharField(max_length=24)),
                ('hands', models.CharField(max_length=24)),
                ('legs', models.CharField(max_length=24)),
                ('feet', models.CharField(max_length=24)),
                ('rating', models.IntegerField(default=0)),
                ('staff_pick', models.BooleanField(default=False)),
            ],
        ),
    ]
