# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='imgs')),
                ('caption', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sets.Image'),
            preserve_default=False,
        ),
    ]
