# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sets', '0002_auto_20160726_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='images',
        ),
        migrations.AddField(
            model_name='set',
            name='images',
            field=models.ManyToManyField(to='Sets.Image'),
        ),
    ]
