# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sets', '0003_auto_20160726_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='title',
            field=models.CharField(default='Caption here', max_length=24),
            preserve_default=False,
        ),
    ]
